name: Pull request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "123456"
          envkey_POSTGRES_DB: "students__tests"
          envkey_DATABASE_URL: "postgres://postgres:123456@db_postgres_github-ci:5432/students__tests"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_app_github-ci npm run test
      - name: Build
        run: npm i && npm run build
